name: Release Please

on:
  push:
    branches: [main]

permissions: {}

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Run Release PR
        uses: chawyehsu/actions/release-pr@9773d15823b8c49b477a78ae968355a3e8fe5cda # v1.2.0
        with:
          private-key: ${{ secrets.RELEASE_MAID_PRIVATE_KEY }}
