name: Release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  # Publish to Crates.io
  cargo_publish:
    name: Publish Cargo Package
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      # Required for OIDC trusted publish to crates.io
      id-token: write
    steps:
      - name: Checkout Source
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup crates.io Auth
        id: auth
        uses: rust-lang/crates-io-auth-action@c6f97d42243bad5fab37ca0427f495c86d5b1a18 # v1.0.5

      - name: Cargo Publish
        run: cargo publish --registry crates-io
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build, cargo_publish]
    steps:
      - name: Draft Release
        uses: chawyehsu/actions/create-release@39efbf77de6aa263da59da5e12ee36e2c1bb174e # v1.3.0
